kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pv-claim
spec:
  storageClassName: jenkins-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: shared-services
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: gcr.io/abdelrahman-377520/jenkins:v1
        ports:
        - containerPort: 8080
        volumeMounts:
            - mountPath: "/var/jenkins_home/"
              name: jenkins-pv
      volumes:
        - name: jenkins-pv
          persistentVolumeClaim:
            claimName: jenkins-pv-claim  
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: shared-services
spec:
  selector:
    app: jenkins
  ports:
  - port: 8080
    targetPort: 8080
    type: LoadBalancer
