kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins
  namespace: shared-services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: shared-services
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: gcr.io/abdelrahman-377520/jenkins:v1
        ports:
         - containerPort: 8080
        volumeMounts:
            - name: jenkins-pv
              mountPath: "/var/"
              subPath: jenkins_home
      volumes:
        - name: jenkins-pv
          persistentVolumeClaim:
            claimName: jenkins
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: shared-services
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
  - port: 8080
    targetPort: 8080
    
