kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nexus
  namespace: shared-services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deployment
  namespace: shared-services
spec:
  selector:
    matchLabels:
      app: nexus
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: gcr.io/abdelrahman-377520/nexus:v1
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-pv
              mountPath: /sonatype-work
          resources:
                limits:
                  memory: "2Gi"
                  cpu: "1000m"
                requests:
                  memory: "1Gi"
                  cpu: "250m"
      volumes:
        - name: nexus-pv
          persistentVolumeClaim:
            claimName: nexus
            readOnly: false 
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: shared-services
spec:
  type: LoadBalancer
  selector:
    app: nexus
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
       
  