kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nexus-pv-claim
spec:
  storageClassName: nexus-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deployment
spec:
  selector:
    matchLabels:
      app: nexus
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: gcr.io/abdelrahman-377520/nexus:v1
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-pv
              mountPath: "/nexus-data"
      volumes:
        - name: nexus-pv
          persistentVolumeClaim:
            claimName: nexus-pv-claim 
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: shared-services
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
       
  