apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: dev  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-backend
  template:
    metadata:
      labels:
        app: app-backend
    spec:
      containers:
        - name: redis
          image: gcr.io/abdelrahman-377520/redis:v1
          ports: 
            - containerPort: 6379


---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: dev  
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: app-backend
